steps:
  - label: ":mag: List directory contents"
    command: ls -R

  - label: ":docker: Build and upload"
    plugins:
      - docker#v5.7.0:
          image: "golang:1.21.0"
          workdir: /app
          volumes:
            - .:/app
          command: ["sh", "-c", "go build -o hello && ls -la"]
    artifact_paths:
      - "hello"

  - block: ":name_input: Enter your name"
    prompt: "Please enter your name"
    fields:
      - text: "Name"
        key: "users-name"
        required: true

  - label: ":golang: Run program"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      ./hello "$(buildkite-agent meta-data get users-name)"

  - wait

  - label: ":memo: Generate report"
    command: |
      echo "Program execution completed for user: $(buildkite-agent meta-data get users-name)" > report.txt
    artifact_paths:
      - "report.txt"
