steps:
  - label: ":mag: List directory contents (on agent)"
    command: |
      echo "Current directory (on agent):"
      pwd
      echo "Directory contents (on agent):"
      ls -la hello/

  - label: ":docker: Build and upload"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.18.0"
          workdir: /go/src/app
          volumes:
            - .:/go/src/app
          command: [
              "/bin/sh",
              "-c",
              "
              echo 'Current directory (in Docker):' &&
              pwd &&
              echo 'Directory contents (in Docker):' &&
              ls -la &&
              echo 'Contents of hello directory:' &&
              ls -la hello/ &&
              echo 'Go environment:' &&
              go env &&
              echo 'Attempting to build:' &&
              cd hello &&
              go build -v -o ../hello &&
              cd .. &&
              echo 'Build complete, directory contents:' &&
              ls -la
              ",
            ]
    artifact_paths:
      - "hello"

  - block: ":name_input: Enter your name"
    prompt: "Please enter your name"
    fields:
      - text: "Name"
        key: "users-name"
        required: true

  - label: ":golang: Run program"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      ./hello "$(buildkite-agent meta-data get users-name)"

  - wait

  - label: ":memo: Generate report"
    command: |
      echo "Program execution completed for user: $(buildkite-agent meta-data get users-name)" > report.txt
    artifact_paths:
      - "report.txt"
