steps:
  - label: ":mag: List directory contents"
    command: |
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Contents of hello directory:"
      ls -la hello/

  - label: ":docker: Build and Upload"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.18.0"
          workdir: /go/src/app
          volumes:
            - .:/go/src/app
          environment:
            - BUILDKITE_AGENT_ACCESS_TOKEN
          command: [
              "/bin/sh",
              "-c",
              "
              cd hello &&
              go build -v -o hello &&
              mkdir -p artifact &&
              mv hello artifact/ &&
              buildkite-agent artifact upload 'artifact/**/*'
              ",
            ]

  - block: ":name_input: Enter your name"
    prompt: "Please enter your name"
    fields:
      - text: "Name"
        key: "users-name"
        required: true

  - label: ":golang: Run the program"
    command: |
      echo "Current directory:"
      pwd
      echo "Directory contents before download:"
      ls -la
      echo "Downloading artifact:"
      buildkite-agent artifact download 'artifact/*' .
      echo "Directory contents after download:"
      ls -la artifact/
      echo "Making executable:"
      chmod +x artifact/hello
      echo "Running program:"
      ./artifact/hello "$(buildkite-agent meta-data get users-name)"

  - wait

  - label: ":memo: Generate report"
    command: |
      echo "Program execution completed for user: $(buildkite-agent meta-data get users-name)" > report.txt
    artifact_paths:
      - "report.txt"
